/** Declaration file generated by dts-gen */

export function load(e: any, ...args: any[]): any;

export function loadView(e: any, ...args: any[]): any;

export namespace load {
    const prototype: {
    };

}

export namespace loadView {
    const prototype: {
    };

}

